name:                hawler
version:             0.1.0.0
github:              "chrispwidener/hawler"
license:             BSD3
author:              "Chris Widener Jr"
maintainer:          "chrispwidener@gmail.com"
copyright:           "2019 Chris Widener"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chrispwidener/hawler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - wreq
  - containers
  - bytestring
  - async
  - tagsoup
  - lens
  - regex
  - http-types

tests:
  hawler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hawler
